POST {{lh6BaseUrl}}/report
Content-Type: application/json

{
  "url": "https://news.saju.dev/",
  "device": "desktop",
  "throttling": "desktopDense4G"
}

###
GET {{lh6BaseUrl}}/ping

###
GET {{lh6BaseUrl}}
